### ISSUE TITLE
Usage Instructions?

### ISSUE THREAD

**Issue by Jimgskoop** [jrajav/jshint2eslint#1]
I'm interested in trying to use jshint2eslint, but there's no documentation or usage instructions....?

**Comment by jonvuri** [comment]
Sorry about that - I updated the README!

Note that this tool is somewhat incomplete (note the TODO's), and also potentially out of date for the current versions of jshint and eslint since I wrote it 10 months ago. That said, at the time I wrote it it worked well for most .jshintrc's found in the wild. If you encounter any issues with it feel free to file them.

**Comment by jonvuri** [comment]
Fixed by 830a134
